var baraja = ["../images/00.png",
					"../images/01.png",
					"./images/02.png",
					"../images/03.png",
					"../images/04.png",
					"../images/05.png",
					"../images/06.png",
					"../images/07.png",
					"../images/08.png",
					"../images/09.png",
					"../images/10.png",
					"../images/11.png",
					"../images/12.png",
					"../images/13.png",
					"../images/14.png",
					"../images/15.png",
					"../images/16.png",
					"../images/17.png",
					"../images/18.png",
					"../images/19.png",
					"../images/20.png",
					"../images/21.png",
				   ];
var sources = {
    reverso: 'images/Reverso.png',
    carta1: 'images/01.png',
    carta2: 'images/02.png',
    carta3: 'images/03.png',
    carta4: 'images/04.png',
    carta5: 'images/05.png',
    carta6: 'images/06.png',
    carta7: 'images/07.png',
    carta8: 'images/08.png',
    carta9: 'images/09.png',
    carta10: 'images/10.png',
    carta11: 'images/11.png',
    carta12: 'images/12.png',
    carta13: 'images/13.png',
    carta14: 'images/14.png',
    carta15: 'images/15.png',
    carta16: 'images/16.png',
    carta17: 'images/17.png',
    carta18: 'images/18.png',
    carta19: 'images/19.png',
    carta20: 'images/20.png',
    carta21: 'images/21.png',
    carta1r: 'images/01r.png',
    carta2r: 'images/02r.png',
    carta3r: 'images/03r.png',
    carta4r: 'images/04r.png',
    carta5r: 'images/05r.png',
    carta6r: 'images/06r.png',
    carta7r: 'images/07r.png',
    carta8r: 'images/08r.png',
    carta9r: 'images/09r.png',
    carta10r: 'images/10r.png',
    carta11r: 'images/11r.png',
    carta12r: 'images/12r.png',
    carta13r: 'images/13r.png',
    carta14r: 'images/14r.png',
    carta15r: 'images/15r.png',
    carta16r: 'images/16r.png',
    carta17r: 'images/17r.png',
    carta18r: 'images/18r.png',
    carta19r: 'images/19r.png',
    carta20r: 'images/20r.png',
    carta21r: 'images/21r.png',
};


var definiciones_arcanos = [
	["EL LOCO","INMADUREZ. ESPONTANEIDAD. PLACER. AVENTURA. VIAJES LARGOS.",
		"La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.",
		"Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.",
		"Carta que sugiere reforzar la concentración."],
	["EL MAGO","CREATIVIDAD. FUERZA DE VOLUNTAD, INICIOS, BUENA SALUD.",
		"La maga sostiene en su mano una vara que actúa de canal o puente entre el mundo espiritual y lo material. Realiza un ritual con velas amarillas (color del intelecto). La armonía que se percibe (la vegetación, las mariposas, el fuego, la petición y la vestimenta blanca y amarillo), nos habla tambien de creación y equilibrio. La orientación puede llegar a través de la propia intuición o en la forma de una persona que provoca el cambio o transformación.",
		"Creatividad. Fuerza de voluntad, inicios, buena salud. La letra hebrea que le corresponde es Aleph. L a nota musical asociada con esta carta es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.",
		"Carta que refuerza la conexión espiritual."],
	["LA SACERDOTISA","EL OCULTISMO. SABIDURÍA. MAESTRA. SOLTERÍA.",
		"La Sacerdotisa está representada como una virgen vestal, pues todo en ella transmite pureza. Su corona de flores simboliza el conocimiento receptivo. Ella sostiene en sus brazos el Libro de los Secretos ocultos, revelados a su conocimiento, pero inaccesibles para el mundo externo. Las columnas en blanco y negro representan la creación, sostenida por universo material y antimaterial.",
		"El Ocultismo. Sabiduría. Maestra. Soltería. La letra hebrea que corresponde es Bet. La nota musical asociada con esta carta es Sol# –que armoniza el chakra 5 (garganta)–, y el color azul cielo.",
		"Carta que refuerza la percepción superior."],
	["LA EMPERATRIZ","EL NACIMIENTO. LOGROS. ESPOSA. RIQUEZA.",
		"La Emperatriz en el Tarot Áurico representa el poder, la sexualidad, la vida, la feminidad, la sensibilidad… Ella es el mundo físico, la fertilidad y el amor incondicional. Es la creación de la vida, del romance, del arte o de los negocios. Su figura es sobreprotectora y a veces posesiva.",
		"El Nacimiento. Logros. Esposa. Riqueza. La letra hebrea que le corresponde es Ghimed. La nota musical asociada con esta carta es Fa# –que armoniza el chakra 4 (corazón)–, y el color verde.",
		"Carta que refuerza dar vida a los deseos."],
	["EL EMPERADOR","FUERZA. PODER. MARIDO. CONFIANZA. RIQUEZA",
		"El Emperador es una figura majestuosa pero que transmite a la vez serenidad. Conoce su poder terrenal y material. Tiene un estatus social alto, pero no se aprovecha de su posición, sino que actúa con bondad. Su expresión sugiere dignidad, paz y capacidad de sacrifico por la familia. Él es la madurez, pero no es una figura espiritual.",
		"Fuerza. Poder. Marido. Confianza. Riqueza. La letra hebrea que le corresponde es Dalet. La nota musical asociada con esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.",
		"Carta que refuerza el poder de la acción."],
	["EL SUMO SACERDOTE","MAESTRO. BONDAD. INSPIRACIÓN. CONTRATO.",
		"El Sumo Sacerdote es el guardián del Conocimiento Universal y el encargado de transmitirlo. Su gorro dorado simboliza el profeta, el guía espiritual en conexión con lo Divino. Su barba es símbolo de sabiduría. Rodeado de antigüos libros y tablas de civilizaciones extintas, sostiene entre sus manos el conocimiento ancestral heredado de los Dioses, pues él es el puente entre la divinidad y la humanidad.",
		"Maestro. Bondad. Inspiración. Contrato. Su letra hebrea es He. La nota musical asociada con esta carta es Do# – que armoniza los chakras 1 y 2 (raiz y sacro)–, y el color rojo-naranja.",
		"Carta que refuerza el conocimiento del sentido de la vida."],
	["LOS ENAMORADOS","AMOR. ELECCIÓN. EXAMEN. TRAMA.",
		"La carta de los enamorados transmite el mensaje de decisiones que hay que tomar y que conllevan sacrificios. El ángel, con su arco, envía la flecha representando el azar que aparentemente rige la decisión… aunque el destino ya ha elegido. La elección no deberá ser tomada a la ligera, pues sus consecuencias van a ser duraderas.",
		"amor, elección, examen, trama. Su letra hebrea es Vau. La nota musical asociada con esta carta es Re – que armoniza el chakra 2 (sacro)–, y el color naranja.",
		"Carta que refuerza el amor y la belleza."],
	["EL CARRO","LUCHA. ADVERSIDAD. ÉXITOS. DECISIONES.",
		"Son los impulsos contradictorios, representados por un caballo blanco y otro negro. Los animales tiran descontroladamente del carro, pues el jinete es el encargado de dominarlos para alcanzar con éxito su objetivo. Todas las necesidades, deseos o cincunstancias, han de ser unidos en una única dirección. La carta alienta la búsqueda de la confianza en uno mismo para vencer en todas las batallas.",
		"Lucha. Adversidad. Éxitos. Decisiones. Viajes. Su letra hebrea es Zayín. La nota musical asociada con esta carta es Re# –que armoniza los chakras 2 y 3 (sacro-plexo solar)–, y el color naranja-amarillo.",
		"Carta que sugiere momentos decisivos en la vida."],
	["LA JUSTICIA","EQUILIBRIO. RECOMPENSA A LARGO PLAZO. SINCERIDAD.",
		"La Justicia se nos presenta para indicar que algo se está desviando del camino trazado originalmente. Ella se inclina levemente hacia su derecha, señalando el error de acercarse a lo material alejándose de lo espiritual. Cuando actuamos de forma justa, no hay necesidad de castigo, o de tener que “poner las cosas en su sitio”. La Justicia expone los hechos tal como son, sin prejuicios. Su posición sentada representa que las cosas se desarrollarán con lentitud.",
		"Equilibrio. Recompensa a largo plazo. Sinceridad. Su letra hebrea es Cheth. La nota musical asociada con esta carta es Fa# –que armoniza el chakra 4 (corazón)–, y el color verde.",
		"Carta que sugiere un equilibrio."],
	["EL ERMITAÑO","SABIO. EXPERIENCIA. SECRETOS. PRUDENCIA. EQUILIBRIO",
		"El ermitaño, que aparece cubierto por un manto desde la cabeza hasta los pies, camina hacia el retiro de una vida austera, sin comodidades. Es momento de reflexión y autorealización espiritual (nunca terrenal). Él busca la soledad para encontrar el equilibrio, aunque el cuervo, en su espera, acecha el aislamiento para ponerle problemas. La luz de la lámpara encarna el espíritu de la virtud, la fe y la vigilancia. El avance es lento pero seguro.",
		"Sabio. Experiencia. Secretos. Prudencia. Equilibrio. Su letra hebrea es Teth. La nota musical asociada con esta carta es Fa –que armoniza el chakra 4 (corazón)–, y el color verde.",
		"Carta que refuerza la emoción espiritual."],
	["LA RUEDA DE LA FORTUNA","CAMBIOS. DESENLACES. GANANCIAS O PÉRDIDAS. AMORES PASIONALES.",
		"La rueda de la fortuna le recuerda que la vida está en permanente cambio. El mundo gira constantemente y, del mismo modo, también nosotros pasamos por fases y ciclos cambiantes, tiempos de alegría y abundancia, y tiempos de escasez y tristeza. El destello de luz que la ilumina en la parte superior le sugiere afrontar los cambios rápidos para poder así continuar su camino.",
		"Cambios. Desenlaces. Ganancias o pérdidas. Amores pasionales. Su letra hebrea es Yoth. La nota musical asociada con esta carta es La# –que armoniza el chakra 6 (frente)–, y el color índigo.",
		"Carta que refuerza la importancia de los ciclos."],
	["LA FUERZA","FUERZA. PODER. ACCIÓN. ENERGÍA. SUERTE",
		"El león representa nuestra parte animal (emociones), y la mujer, la parte humana (mente). Ella sabe hasta dónde puede controlar su fuerza para manejar todas las energias físicas u ocultas, pues conoce bien sus capacidades. De igual forma, debemos confiar en nosotros mismos para tomar las decisiones correctas y ser capaces de afrontar las consecuencias.",
		"Fuerza. Poder. Acción. Energía. Suerte. Realización personal. Su letra hebrea es Kath. La nota musical asociada a esta carta es Mi –que armoniza los chakras 4 y 3 (corazón-plexo solar)–, y el color verde-amarillo.",
		"Carta que refuerza la fusión entre lo espiritual y lo terrenal."],
	["EL COLGADO","Carta que refuerza la fusión entre lo espiritual y lo terrenal.",
		"La mujer está colgada por los pies, aunque en realidad ningún nudo la sujeta. Ella sabe que nada le impide liberarse, pero se siente bloqueada y no encuentra el momento de actuar. Es momento de abandonar sueños inalcanzables por metas más realistas. Su falta de motivación puede crearle una depresión. La desnudez representa su manera de afrontar los problemas: con dejadez.",
		"Impotencia. Abandono. Sacrificio. Su letra hebrea es Lameth. La nota musical asociada a esta carta es Sol# –que armoniza el chakra 5 (garganta)–, y el color azul.",
		"Carta que sugiere reforzar la mente."],
	["LA TRANSFORMACION","CAMBIOS. PÉRDIDAS. FINAL DE UNA SITUACIÓN. EVOLUCIÓN.",
		"La transformación es un renacimiento, un nuevo comienzo. La muerte de los viejos ideales que ya no sirven. Aquí la figura se halla al lado de un río que representa un viaje a nuestro destino. Cuando aparece la carta de la transformación en una situación en la que el miedo nos bloquea o nos retrasa, ella es justo lo que necesitamos para avanzar.",
		"Cambios. Pérdidas. Final de una situación. Evolución. Su letra hebrea es Mem. La nota musical asociada a esta carta es Sol –que armoniza los chakras 4 y 5 (corazón y garganta)–, y el color azul- verdoso.",
		"Carta que refuerza la transformación."],
	["LA TEMPLANZA","SANACIÓN. PACIENCIA. CONSOLIDACIÓN. ESTABILIDAD. CONVERSACIONES.",
		"El ángel pasa el agua de un cuenco a otro sin derramarla. Promueve la unidad y la moderación de los extremos. Controla la situación. Sabe que nada va a pasar. Su vestido de color oro representa lo divino. Ella está dentro del agua y por eso se encuentra en equilibrio en el presente, fluyendo la energía de forma natural en nuestro interior, armonizando y creando una sensación de paz y claridad de pensamiento.",
		"Sanación. Paciencia. Consolidación. Estabilidad. Su letra hebrea es Nun. La nota musical asociada a esta carta es Sol# –que armoniza el chakra 5 (garganta)–, y el color azul.",
		"Carta que domina la percepción superior."],
	["EL DIABLO","LUCHAS. AUTOCASTIGO. ESCLAVITUD. PASIONES",
		"El Diablo es un ángel caído. Él ayuda a dar rienda suelta a los instintos animales reprimidos que todos tenemos dentro. El Diablo exhibe todo su poder apoyando su peso sobre el hombre, al que maneja como si fuera una marioneta. Los que alguna vez estuvieron conectados entre sí por el amor, están ahora unidos al diablo por sus cadenas de lujuria y de ignorancia. Si está dispuesto a liberarse de esas cadenas, podrá caminar hacia la luz.",
		"Luchas. Autocastigo. Esclavitud. Pasiones. Su letra hebrea es Samech. La nota musical asociada a esta carta es La# –que armoniza el chakra 6 (frente)–, y el color índigo.",
		"Carta que refuerza el peso del Karma en la consulta."],
	["LA TORRE","CAOS. RUPTURAS. CAMBIOS. PÉRDIDAS. PROBLEMAS.",
		"La Torre aparece partida por la mitad. Representa el colapso de una estructura o de su actual manera de vivir. Plantea transformaciones que crean un desequilibrio emocional, espiritual y terrenal. Busque solidez para empezar una nueva etapa.",
		"Caos. Rupturas. Cambios. Pérdidas. Problemas. Su letra hebrea es Hain. La nota musical asociada a esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.",
		"Carta que refuerza los cambios."],
	["LA ESTRELLA","ESPERANZA. REALIZACIÓN. OPORTUNIDAD. BUENA SALUD. HIJOS.",
		"La Estrella tiene una luz fuerte e intensa, que representa la Justicia Divina. Las estrellas son un símbolo de esperanza, de regeneración, la visión de esa nueva vida que has anhelado. Cuando aparece la Estrella, su vida está a punto de ser algo más fácil. Las fuerzas de la vida se combinan para ayudar, no para presentar obstáculos en tu camino.",
		"Esperanza. Realización. Oportunidad. Buena salud. Hijos. Su letra hebrea es Pei. La nota musical asociada a esta carta es La# –que armoniza el chakra 6 (frente)–, y el color índigo.",
		"Carta que refuerza el orden de la vida."],
	["LA LUNA","NEGATIVIDAD. DECEPCIÓN. ENGAÑO. FALSEDAD. MIEDOS.",
		"La Luna representa la bipolaridad constante a la hora de encontrar soluciones a los problemas. El cangrejo, en sus pies, indica retroceder al pasado para no enfrentar el esfuerzo de avanzar hacia el futuro. La Luna afecta a nuestras emociones porque vienen de la parte oculta interior de nosotros. Ella es la precursora de los miedos internos, que nos impiden enfrentar las situaciones, y que pueden degenerar en una enfermedad física o mental.",
		"Negatividad. Decepción. Engaño. Falsedad. Miedos. Su letra hebrea es Tzade. La nota musical asociada a esta carta es Si –que armoniza el chakra 7 (corona)–, y el color violeta.",
		"Carta que refuerza el orden de los ciclos vitales."],
	["EL SOL","AMOR. LOGROS. ÉXITOS. AMISTAD. HOGAR. MATRIMONIO",
		"Los rayos del Sol sobre las niñas transmiten alegría, equilibrio, felicidad. Otorgan fertilidad y abundancia. Esto tiene que ver con los cambios, los ciclos de la vida: nacimiento, vida, muerte y renacimiento. Esta es una carta feliz. Inspira despreocupación, “buenas vibraciones”. Trae uniones duraderas con mucho amor. El sol es el rey de todos los astros, y el que otorga éxito a todas las situaciones de la vida.",
		"Amor. Logros. Éxitos. Amistad. Hogar. Matrimonio. Su letra hebrea es Qoph. La nota musical asociada a esta carta es Re –que armoniza el chakra 2 (sacro)–, y el color naranja.",
		"Carta que refuerza el éxito en la consulta."],
	["EL JUICIO","DESPERTAR. JUICIO. SENTENCIA A FAVOR.",
		"Despertar. Juicio. Sentencia a favor. Su letra hebrea es Resh. La nota musical asociada a esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.",
		"Carta que refuerza acción y cambio."],
	["EL MUNDO","PLENITUD. REALIZACIÓN. UNIÓN. ÉXITO. CAMBIO DEFINITIVO. BODA",
		"La mujer aparece acompañada de un hombre. Ambos se fusionan entre sí en un abrazo que simboliza la culminación, la plenitud de la energía generadora de triunfos. El Mundo es la finalización, el cumplimiento, el potencial, los resultados, las realizaciones, la integridad, el éxito, la totalidad… Simboliza también asuntos o viajes en el extranjero, el éxito al final de los proyectos y el logro de metas.",
		"Plenitud. Realización. Unión. Éxito. Cambio definitivo. Boda. Su letra hebrea es Shin. La nota musical asociada con esta carta es La –que armoniza el chakra 6 (frente)–, y el color índigo.",
		"Carta que refuerza el significado de consumación."],
];




var textos_dia =[
		"El Loco: Hoy puedes tener un día algo movido. Tendrás la cabeza como despistada y, si vas a comenzar algo, piénsalo dos veces antes de hacerlo: puede que no sea oro todo lo que reluce, y cualquier movimiento podría ser un fracaso a la larga. Trabaja el chakra 3 (plexo solar), cantando el mantra RAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca por la noche. ",
	    "El Mago: Hoy se presenta un día con mucha fuerza interior. Aprovéchala para ser creativo en lo que hagas, pues eso puede darte la llave a otras cosas más adelante. Los que te conocen saben muy bien lo que vales, así que enséñales que aún puedes hacer más. Trabaja el chakra 3 (plexo solar), cantando el mantra RAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
    	"La Sacerdotisa: Hoy es un día que puedes aprender mucho de las cosas que te ocurran. Tu sentido común sabrá  como recogerlo para integrarlo más adelante. La paciencia jugará en tu contra, así que echa mano de tu serenidad para equilibrar la situación. Trabaja el chakra 5 (garganta), cantando el mantra HAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "La Emperatriz: Eres una persona muy intuitiva, y eso hará más fácil equilibrar a las personas que te rodean. Hoy eres tú quien maneja el día; no dejes que nadie lo haga por ti. Cree en tu gran fuerza interior, y ponla en práctica. Trabaja el chakra 4 (corazón), cantando el mantra YAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "El Emperador: Hoy es un gran día para afianzar tu confianza en ti mismo. Hay muchos motivos a tu alrededor que así lo indican, así que saca esa espíritu INDOMABLE que tienes dentro y que lo vea todo el mundo. Consigue tus metas, SABES que puedes. Trabaja el chakra 1 (raíz), cantando el mantra LAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
	    "El Sumo Sacerdote: Día sereno. No te refugies en la timidez o, de lo contrario, puedes dejar escapar algún momento importante, y eso no sería bueno para ti. Eres muy noble, por eso siempre los que te rodean acuden a ti con sus problemas. Absorbe sólo lo que tú creas que merece la pena. Trabaja el chakra 1 y 2 (raíz y sacro), cantando el mantra LAM y VAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
	    "Los enamorados: Hoy pueden aflorar recuerdos del pasado que, aunque creas tenerlos superados siguen ahí en tu pensamientos. Necesitas confiar más en ti, saber lo mucho que vales, y afrontar así el día con más optimismo. Recuerda que eres un ser con mucha pasión: no la anules. Trabaja el chakra 2 (sacro), cantando el mantra VAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "El carro:  Hoy tendrás dualidad de pensamientos; manéjalos bien y sabrás el camino que tienes que tomar. Recuerda que sólo tú tienes el poder de manejar tu vida. Tu necesidad de querer siempre más en todos los aspectos, es el reflejo de la lucha que sufre tu ser interior. Trabaja el chakra 2 y 3 (sacro y plexo solar), cantando el mantra VAM y  RAM para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "La Justicia:Aprovecha el día para aclarar malos entendidos. Puede que no te den toda la razón, pero no te preocupes: la verdad se inclinará más a tu favor. Lo importante es que tengas armonía en tu interior. Lograrás tomar la perspectiva correcta y visualizar así tu justa recompensa. Hay que ser siempre valiente.Trabaja el chakra 4 (corazón), para que el día fluya con armonía, cantando el mantra Yam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El Ermitaño:Cuidado con lo que hablas. Sé prudente, incluso si eso significa evitar alguna conversación. No lo dudes, no es día propicio para realizar movimientos. Eres un ser que sabe muchas cosas, pero a veces es mejor callarlas.Tu discreción te servirá para madurar conocimientos y saber actuar más adelante. Trabaja el chakra 4 (corazón), para que el día fluya con armonía, cantando el mantra Yam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Rueda: Hoy puede ser un gran día para dar la vuelta a tu situación. Eres un ser con capacidad para realizar cualquier cosa que se proponga. Sólo tienes que coger esa fuerza para cambiar de rumbo. Hay muchas personas que te apoyan, así que no te sientas en soledad.Trabaja el chakra 6 (frente), para que el día fluya con armonía, cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Fuerza: Hoy puedes aprovechar la fuerza que te da el día para hacer cosas que tienes pendientes. Sin embargo, ten en cuenta que a veces esa fuerza puede volverse en tu contra, dependiendo de tus comentarios o acciones. Recuerda que el día se acaba pero las palabras se quedan.Trabaja el chakra 3 y 4 (plexo solar y corazón), para que el día fluya con armonía, cantando el mantra Yam y Ram.. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El Colgado: Hoy puede ser una jornada pesada y algo densa. No dejes las cosas para otro día, busca las fuerza que tienes dentro para realizar tu cometido. Recuérdate a ti mismo que eres una persona muy válida. Los obstáculos sólo supondrán un retraso, y aún tienes muchos proyectos pendientes por llegar.Trabaja el chakra 5 (garganta), para que el día fluya con armonía, cantando el mantra Ham. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Transformación: Día para meditar los cambios que han llegado a tu vida. Intenta dar la vuelta a esa preocupación, aunque no sepas exactamente cómo; tendrás todo el día para descubrirlo. Haz una lista de las cosas que aún esperas realizar, y tenla siempre presente. Eso hará que tomes consciencia para hacerlas realidad en el momento en que te sientas con la fuerza suficiente.Trabaja el chakra 4 y 5 (corazón y garganta), para que el día fluya con armonía, cantando el mantra Ham y Yam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Templanza: Ten paciencia con todo lo que tengas que hacer. Aunque te adaptas a casi todo, debes aprender a administrar tus emociones. No es buen día para enseñarlas, pues te mostraría frágil y vulnerable a ojos de los demás. Conseguirás lo que te propongas.Trabaja el chakra 5 (garganta), para que el día fluya con armonía, cantando el mantra Ham. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El Diablo: Tal vez hoy te encuentres con alguien que te envidie o te mienta. Eres una persona inteligente y con un muy buen halo de energía. Pero eso también puede crear envidias y críticas a tu alrededor. No es buen día para tomar decisiones importantes.  Trabaja el chakra 6 (frente), para que el día fluya con armonía, cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Torre: No pierdas tu estabilidad, recuérdate que eres fuerte y que nada puede desequilibrarte. Hoy tus creencias pueden derrumbarse, pero a causa de las circunstancias que te rodean: no por la realidad. Aprovecha los cambios para tomar consciencia de la situación que vives, y pronto sabrás cómo encauzar las cosas.Trabaja el chakra 1 (raiz), para que el día fluya con armonía, cantando el mantra Lam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Estrella: No mezcles el pasado con el presente, cada uno ha tenido su momento. Tu fe hará posible convertir en realidad tus sueños, pero ellos no deben ser utopías. Tienes muchas oportunidades ante ti. Reflexiona si te convienen y déjate llevar; quizás te sorprendan.Trabaja el chakra 6 (frente), para que el día fluya con armonía, cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Luna: No es un buen día para hacer proyectos o tomar decisiones. Tu mente podría jugarte una mala pasada a la hora de realizar algo. Tus pensamientos se mueven en una dualidad poco clara, así que no hagas nada de lo que más adelante puedas arrepentirte. La prudencia será tu mejor aliada. ",
        "El Sol: Eres genial y mereces tomarte un día sólo para ti. Siempre estás pensando en los demás, pero hoy toca mimarte y cuidarte, pues tu cuerpo necesita un descanso. Sal y diviértete; hazte ese regalo. Hoy debes ser tú lo primero. Trabaja el chakra 2 (el sacro), para que el día fluya con armonía, cantando el mantra Vam. Siempre por la mañana de uno a cinco minutos, nunca de noch",
        "El juicio: Puede que vivas un momento de injusticia, así que no es momento de hablar cosas pendientes. Han habido oportunidades para resolver esos asuntos que se han ido dilatando en el tiempo, pero no es hoy el momento de hacerlo. No saldrían como tú hubieras deseado. Trabaja el chakra 1 (raiz), para que el día fluya con armonía, cantando el mantra Lam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El mundo: Gran día para recoger felicitaciones y agradecimientos por los esfuerzos habituales que realizas en tu vida. Tus penas se convertirán pronto en merecidas alegrías, y ese día está hoy más cerca de ti. Trabaja el chakra 6 (frente), para que el día fluya con armonía. Cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche."
]
