var baraja = ["../images/00.jpg",
					"../images/01.jpg",
					"./images/02.jpg",
					"../images/03.jpg",
					"../images/04.jpg",
					"../images/05.jpg",
					"../images/06.jpg",
					"../images/07.jpg",
					"../images/08.jpg",
					"../images/09.jpg",
					"../images/10.jpg",
					"../images/11.jpg",
					"../images/12.jpg",
					"../images/13.jpg",
					"../images/14.jpg",
					"../images/15.jpg",
					"../images/16.jpg",
					"../images/17.jpg",
					"../images/18.jpg",
					"../images/19.jpg",
					"../images/20.jpg",
					"../images/21.jpg",
				   ];

var definiciones_arcanos = [
	"<h1 style=\'text-align:center; font-size: 20px\'>EL LOCO</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
"<h1 style='text-align:center; font-size: 20px'>EL MAGO</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",

"<h1 style='text-align:center; font-size: 20px'>LA SACERDOTISA</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
	"<h1 style='text-align:center; font-size: 20px'>LA EMPERATRIZ</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
	"<h1 style='text-align:center; font-size: 20px'>EL EMPERADOR</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
	"<h1 style='text-align:center; font-size: 20px'>EL SUMO SACERDOTE</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
	
		"<h1 style='text-align:center; font-size: 20px'>LOS ENAMORADOS</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>EL CARRO</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
	"<h1 style='text-align:center; font-size: 20px'>LA JUSTICIA</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>EL ERMITAÑO</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>LA RUEDA DE LA FORTUNA</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>LA FUERZA</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>EL COLGADO</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>TRANSFORMACION</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>LA TEMPLANZA</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>EL DIABLO</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>LA TORRE</h1><p>La figura que aparece es femenina. Llama la atención su atuendo de colores llamativos, lo que indica que su personalidad aún está por definir. No tiene miedo de adentrarse en un bosque desconocido, que representa el inicio a un futuro que todavía no tiene un rumbo definido. En sus manos está el camino de la superación. Ese viaje a lo desconocido le aportará las experiencias necesarias para su evolución.</p><p><mark>Significado:</mark> Inmadurez. Espontaneidad. Placer. Aventura. Viajes largos. Su letra hebrea es Tau. La nota musical asociada a esta figura es Mi –que armoniza el chakra 3 (plexo solar)–, y el color amarillo.</p><p>Carta que sugiere reforzar la concentración.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>LA ESTRELLA</h1><p>Un ángel anunciador llega para advertir que todo lo que está oculto será revelado y los engaños descubiertos. Es hora de empezar una nueva vida a partir de las lecciones del pasado. Si está dispuesto a admitir sus errores, resurgirá reforzado. Es el momento de renovar cualquier proyecto.</p><p><mark>Significado:</mark> Despertar. Juicio. Sentencia a favor. Su letra hebrea es Resh. La nota musical asociada a esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.</p><p>Carta que refuerza acción y cambio.</p>",
	
		"<h1 style='text-align:center; font-size: 20px'>LA LUNA</h1><p>Un ángel anunciador llega para advertir que todo lo que está oculto será revelado y los engaños descubiertos. Es hora de empezar una nueva vida a partir de las lecciones del pasado. Si está dispuesto a admitir sus errores, resurgirá reforzado. Es el momento de renovar cualquier proyecto.</p><p><mark>Significado:</mark> Despertar. Juicio. Sentencia a favor. Su letra hebrea es Resh. La nota musical asociada a esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.</p><p>Carta que refuerza acción y cambio.</p>",

		"<h1 style='text-align:center; font-size: 20px'>EL SOL</h1><p>Un ángel anunciador llega para advertir que todo lo que está oculto será revelado y los engaños descubiertos. Es hora de empezar una nueva vida a partir de las lecciones del pasado. Si está dispuesto a admitir sus errores, resurgirá reforzado. Es el momento de renovar cualquier proyecto.</p><p><mark>Significado:</mark> Despertar. Juicio. Sentencia a favor. Su letra hebrea es Resh. La nota musical asociada a esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.</p><p>Carta que refuerza acción y cambio.</p>",
	
	"<h1 style='text-align:center; font-size: 20px'>EL JUICIO</h1><p>Un ángel anunciador llega para advertir que todo lo que está oculto será revelado y los engaños descubiertos. Es hora de empezar una nueva vida a partir de las lecciones del pasado. Si está dispuesto a admitir sus errores, resurgirá reforzado. Es el momento de renovar cualquier proyecto.</p><p><mark>Significado:</mark> Despertar. Juicio. Sentencia a favor. Su letra hebrea es Resh. La nota musical asociada a esta carta es Do –que armoniza el chakra 1 (raiz)–, y el color rojo.</p><p>Carta que refuerza acción y cambio.</p>",
	

	"<h1 style='text-align:center; font-size: 20px'>EL MUNDO</h1><p>La mujer aparece acompañada de un hombre. Ambos se fusionan entre sí en un abrazo que simboliza la culminación, la plenitud de la energía generadora de triunfos. El Mundo es la finalización, el cumplimiento, el potencial, los resultados, las realizaciones, la integridad, el éxito, la totalidad… Simboliza también asuntos o viajes en el extranjero, el éxito al final de los proyectos y el logro de metas.</p><p><mark>Significado:</mark> Plenitud. Realización. Unión. Éxito. Cambio definitivo. Boda. Su letra hebrea es Shin. La nota musical asociada con esta carta es La –que armoniza el chakra 6 (frente)–, y el color índigo.</p>Carta que refuerza el significado de consumación."
	
];


var textos_dia =[
	"El Loco: Hoy puedes tener un día algo movido. Tendrás la cabeza como despistada y, si vas a comenzar algo, piénsalo dos veces antes de hacerlo: puede que no sea oro todo lo que reluce, y cualquier movimiento podría ser un fracaso a la larga. Trabaja el chakra 3 (plexo solar), cantando el mantra RAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca por la noche. ",
	    "El Mago: Hoy se presenta un día con mucha fuerza interior. Aprovéchala para ser creativo en lo que hagas, pues eso puede darte la llave a otras cosas más adelante. Los que te conocen saben muy bien lo que vales, así que enséñales que aún puedes hacer más. Trabaja el chakra 3 (plexo solar), cantando el mantra RAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
    	"La Sacerdotisa: Hoy es un día que puedes aprender mucho de las cosas que te ocurran. Tu sentido común sabrá  como recogerlo para integrarlo más adelante. La paciencia jugará en tu contra, así que echa mano de tu serenidad para equilibrar la situación. Trabaja el chakra 5 (garganta), cantando el mantra HAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "La Emperatriz: Eres una persona muy intuitiva, y eso hará más fácil equilibrar a las personas que te rodean. Hoy eres tú quien maneja el día; no dejes que nadie lo haga por ti. Cree en tu gran fuerza interior, y ponla en práctica. Trabaja el chakra 4 (corazón), cantando el mantra YAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "El Emperador: Hoy es un gran día para afianzar tu confianza en ti mismo. Hay muchos motivos a tu alrededor que así lo indican, así que saca esa espíritu INDOMABLE que tienes dentro y que lo vea todo el mundo. Consigue tus metas, SABES que puedes. Trabaja el chakra 1 (raíz), cantando el mantra LAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
	     "El Sumo Sacerdote: Día sereno. No te refugies en la timidez o, de lo contrario, puedes dejar escapar algún momento importante, y eso no sería bueno para ti. Eres muy noble, por eso siempre los que te rodean acuden a ti con sus problemas. Absorbe sólo lo que tú creas que merece la pena. Trabaja el chakra 1 y 2 (raíz y sacro), cantando el mantra LAM y VAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
	    "Los enamorados: Hoy pueden aflorar recuerdos del pasado que, aunque creas tenerlos superados siguen ahí en tu pensamientos. Necesitas confiar más en ti, saber lo mucho que vales, y afrontar así el día con más optimismo. Recuerda que eres un ser con mucha pasión: no la anules. Trabaja el chakra 2 (sacro), cantando el mantra VAM, para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "El carro:  Hoy tendrás dualidad de pensamientos; manéjalos bien y sabrás el camino que tienes que tomar. Recuerda que sólo tú tienes el poder de manejar tu vida. Tu necesidad de querer siempre más en todos los aspectos, es el reflejo de la lucha que sufre tu ser interior. Trabaja el chakra 2 y 3 (sacro y plexo solar), cantando el mantra VAM y  RAM para que el día fluya con armonía. Por la mañana de uno a cinco minutos, nunca de noche.",
        "La Justicia:Aprovecha el día para aclarar malos entendidos. Puede que no te den toda la razón, pero no te preocupes: la verdad se inclinará más a tu favor. Lo importante es que tengas armonía en tu interior. Lograrás tomar la perspectiva correcta y visualizar así tu justa recompensa. Hay que ser siempre valiente.Trabaja el chakra 4 (corazón), para que el día fluya con armonía, cantando el mantra Yam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El Ermitaño:Cuidado con lo que hablas. Sé prudente, incluso si eso significa evitar alguna conversación. No lo dudes, no es día propicio para realizar movimientos. Eres un ser que sabe muchas cosas, pero a veces es mejor callarlas.Tu discreción te servirá para madurar conocimientos y saber actuar más adelante. Trabaja el chakra 4 (corazón), para que el día fluya con armonía, cantando el mantra Yam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Rueda: Hoy puede ser un gran día para dar la vuelta a tu situación. Eres un ser con capacidad para realizar cualquier cosa que se proponga. Sólo tienes que coger esa fuerza para cambiar de rumbo. Hay muchas personas que te apoyan, así que no te sientas en soledad.Trabaja el chakra 6 (frente), para que el día fluya con armonía, cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Fuerza: Hoy puedes aprovechar la fuerza que te da el día para hacer cosas que tienes pendientes. Sin embargo, ten en cuenta que a veces esa fuerza puede volverse en tu contra, dependiendo de tus comentarios o acciones. Recuerda que el día se acaba pero las palabras se quedan.Trabaja el chakra 3 y 4 (plexo solar y corazón), para que el día fluya con armonía, cantando el mantra Yam y Ram.. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El Colgado: Hoy puede ser una jornada pesada y algo densa. No dejes las cosas para otro día, busca las fuerza que tienes dentro para realizar tu cometido. Recuérdate a ti mismo que eres una persona muy válida. Los obstáculos sólo supondrán un retraso, y aún tienes muchos proyectos pendientes por llegar.Trabaja el chakra 5 (garganta), para que el día fluya con armonía, cantando el mantra Ham. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Transformación: Día para meditar los cambios que han llegado a tu vida. Intenta dar la vuelta a esa preocupación, aunque no sepas exactamente cómo; tendrás todo el día para descubrirlo. Haz una lista de las cosas que aún esperas realizar, y tenla siempre presente. Eso hará que tomes consciencia para hacerlas realidad en el momento en que te sientas con la fuerza suficiente.Trabaja el chakra 4 y 5 (corazón y garganta), para que el día fluya con armonía, cantando el mantra Ham y Yam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Templanza: Ten paciencia con todo lo que tengas que hacer. Aunque te adaptas a casi todo, debes aprender a administrar tus emociones. No es buen día para enseñarlas, pues te mostraría frágil y vulnerable a ojos de los demás. Conseguirás lo que te propongas.Trabaja el chakra 5 (garganta), para que el día fluya con armonía, cantando el mantra Ham. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El Diablo: Tal vez hoy te encuentres con alguien que te envidie o te mienta. Eres una persona inteligente y con un muy buen halo de energía. Pero eso también puede crear envidias y críticas a tu alrededor. No es buen día para tomar decisiones importantes.  Trabaja el chakra 6 (frente), para que el día fluya con armonía, cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Torre: No pierdas tu estabilidad, recuérdate que eres fuerte y que nada puede desequilibrarte. Hoy tus creencias pueden derrumbarse, pero a causa de las circunstancias que te rodean: no por la realidad. Aprovecha los cambios para tomar consciencia de la situación que vives, y pronto sabrás cómo encauzar las cosas.Trabaja el chakra 1 (raiz), para que el día fluya con armonía, cantando el mantra Lam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Estrella: No mezcles el pasado con el presente, cada uno ha tenido su momento. Tu fe hará posible convertir en realidad tus sueños, pero ellos no deben ser utopías. Tienes muchas oportunidades ante ti. Reflexiona si te convienen y déjate llevar; quizás te sorprendan.Trabaja el chakra 6 (frente), para que el día fluya con armonía, cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "La Luna: No es un buen día para hacer proyectos o tomar decisiones. Tu mente podría jugarte una mala pasada a la hora de realizar algo. Tus pensamientos se mueven en una dualidad poco clara, así que no hagas nada de lo que más adelante puedas arrepentirte. La prudencia será tu mejor aliada. ",
        "El Sol: Eres genial y mereces tomarte un día sólo para ti. Siempre estás pensando en los demás, pero hoy toca mimarte y cuidarte, pues tu cuerpo necesita un descanso. Sal y diviértete; hazte ese regalo. Hoy debes ser tú lo primero. Trabaja el chakra 2 (el sacro), para que el día fluya con armonía, cantando el mantra Vam. Siempre por la mañana de uno a cinco minutos, nunca de noch",
        "El juicio: Puede que vivas un momento de injusticia, así que no es momento de hablar cosas pendientes. Han habido oportunidades para resolver esos asuntos que se han ido dilatando en el tiempo, pero no es hoy el momento de hacerlo. No saldrían como tú hubieras deseado. Trabaja el chakra 1 (raiz), para que el día fluya con armonía, cantando el mantra Lam. Siempre por la mañana de uno a cinco minutos, nunca de noche.",
        "El mundo: Gran día para recoger felicitaciones y agradecimientos por los esfuerzos habituales que realizas en tu vida. Tus penas se convertirán pronto en merecidas alegrías, y ese día está hoy más cerca de ti. Trabaja el chakra 6 (frente), para que el día fluya con armonía. Cantando el mantra Om. Siempre por la mañana de uno a cinco minutos, nunca de noche."
]
